# Generated by Django 4.0.4 on 2022-06-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.userprofile'),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
